### ISSUE TITLE
[ERROR] Async loop died! org.zeromq.ZMQException: Address already in use(0x62)

### ISSUE THREAD

**Issue by Researchercs** [zeromq/jzmq#395] opened 2015-12-05 06:52 UTC
I'm new to Ubuntu I got this error

[ERROR] Async loop died! org.zeromq.ZMQException:
Address already in use(0x62)
at org.zeromq.ZMQ$Socket.bind(Native Method)
at zilch.mq$bind.invoke(mq.clj:69)
at backtype.storm.messaging.zmq.ZMQContext.bind(zmq.clj:57)at backtype.storm.messaging.loader$launch_receive_thread_BANG_$fn__1629.invoke(loader.clj:26)
at backtype.storm.util$async_loop$fn__465.invoke(util.clj:375)
at clojure.lang.AFn.run(AFn.java:24) at java.lang.Thread.run(Unknown Source)

 when i tried to connect `port 6703 and 6702` .. by searching i found that problem due to indeed a port conflict. It turns out  ephemeral port range was messed up on the machines
I tried to change number of range in `/proc/sys/net/ipv4/ip_local_port_range`  to `49152 65535` but didn't work
I’m on `Ubuntu 14.04 LTS via vmware` if that is important to know ..
how can I extend range to 64 k or anyone have another idea about this ?

**Comment by beginneer** [comment] 2015-12-25 19:14
any help ?

**Comment by sjohnr** [comment] 2015-12-25 23:11
Seems like you're using Storm, which in turn uses jzmq. Is that correct? If that's the case:
1. I thought Storm switched away from ZeroMQ some time ago. What version are you using?
2. I think you would want to direct the question to the Storm project instead.
3. Doesn't seem like a port problem. It's either a bug, or there are too many servers, possibly.

**Comment by Researchercs** [comment] 2015-12-26 06:26
thanks for your replying ,
- that's right it's storm i asked them but couldn't fix it until now .
- i'm using storm-0.8.2 but i upgraded this version and got same error by
different name like "cannot bind port : x"
- but i have to use this version first , i posted that it's bug  but no one
answer too
- do you have any knowledge about storm configuration ? i hope that

**Comment by sjohnr** [comment] 2015-12-27 03:04
Sorry, I don't know much about storm configuration. I've used it in a single-node cluster and that's about it. But the version I used doesn't use ZeroMQ anyway.

But I'm guessing your config is wrong then. It's probably not a bug. Maybe try their mailing group and send your configs. Someone may spot your problem.

**Comment by Researchercs** [comment] 2015-12-27 22:00
thanks for replying , just i want to ask you in the basic
i think i have  misunderstading in the logic of storm , what i know it has
2 models
1: local
2: production or distribute

for run local . i ran the code with maven and worked well
now i want to run it in production so i have ly laptop but not network so i
will not able to run it in production right ?

**Comment by trevorbernard** [comment] 2015-12-27 22:05
Hi @Researchercs, I don't believe you will find much help here. I'm going to close this issue because it's not relevant to JZMQ. As @sjohnr said, you're best bet is to ask the storm mailing list or check out stackoverflow.

**Closed by trevorbernard** 2015-12-27 22:05 UTC

**Comment by Researchercs** [comment] 2015-12-27 22:25
thanks , but can you delete my last comment ?

**Comment by trevorbernard** [comment] 2015-12-27 22:31
Sure, comment deleted.
